In [3]:
#parser: given owl, set up db and write mappings

In [7]:
with open ("../books/books_20_07.owl", "r") as fowl:
    content = fowl.read()
    i = 0
    lines = content.split("\n")
    outstring = ""
    dict_classes = {}
    dict_relations = {}
    dict_attributes = {}
    while (i < len(lines)):
        
        line = lines[i]
        
        if ("follows") in line or ("bo:author_genre" in line and "bo:Book" in line):
            i += 1
            continue
        
        if "Prefix" in lines[i]:
            i += 1
            continue

        if "Declaration(Class" in lines[i]: #from now on, work on this class
            classe = line.split(":")[1][:-2]
            dict_classes[classe] = {}
            dict_classes[classe]["attributes"] = {}
            i += 1
            continue
            
        if "Declaration(ObjectProperty" in lines[i]:
            relation = line.split(":")[1][:-2]
            dict_relations[relation] = {}
            dict_relations[relation]["functional"] = False
            dict_relations[relation]["inv_functional"] = False
            i += 1
            continue
        
        if "Declaration(DataProperty" in lines[i]:
            attribute = line.split(":")[1][:-2]
            dict_attributes[attribute] = {}
            dict_attributes[attribute]["functional"] = False
            dict_attributes[attribute]["inv_functional"] = False
            i += 1
            continue
            
        if "ObjectPropertyDomain" in lines[i]:
            relation = line.split(" ")[0].split(":")[-1]
            domain = line.split(":")[-1][:-1]
            dict_relations[relation]["domain"] = {}
            dict_relations[relation]["domain"]["name"] = domain
            dict_relations[relation]["domain"]["nullable"] = True
            i += 1
            continue
            
        if "DataPropertyDomain" in lines[i]:
            attribute = line.split(" ")[0].split(":")[-1]
            domain = line.split(":")[-1][:-1]
            dict_attributes[attribute]["domain"] = {}
            dict_attributes[attribute]["domain"]["name"] = domain
            dict_attributes[attribute]["domain"]["nullable"] = True
            i += 1
            continue
        
        if "ObjectPropertyRange" in lines[i]:
            relation = line.split(" ")[0].split(":")[-1]
            range_ = line.split(":")[-1][:-1]
            dict_relations[relation]["range"] = {}
            dict_relations[relation]["range"]["name"] = range_
            dict_relations[relation]["range"]["nullable"] = True
            i += 1
            continue
            
        if "DataPropertyRange" in lines[i]:
            attribute = line.split(" ")[0].split(":")[-1]
            range_ = line.split(":")[-1][:-1]
            dict_attributes[attribute]["range"] = {}
            dict_attributes[attribute]["range"]["name"] = range_
            #dict_attributes[attribute]["range"]["nullable"] = True
            i += 1
            continue
        
        if "FunctionalObjectProperty" in lines[i]:
            relation = line.split(":")[-1][:-1]
            dict_relations[relation]["functional"] = True
            i += 1
            continue
            
        if "FunctionalDataProperty" in lines[i]:
            attribute = line.split(":")[-1][:-1]
            dict_attributes[attribute]["functional"] = True
            i += 1
            continue

        if "EquivalentClasses" in lines[i] and "Thing" in lines[i]:
            relation = line.split(":")[2].split(" ")[0].replace(")", "")
            if "ObjectInverseOf" not in lines[i]:
                domain = line.split(":")[1].split(" ")[0]
                dict_relations[relation]["domain"]["nullable"] = False
            else:
                range_ = line.split(":")[1].split(" ")[0]
                dict_relations[relation]["range"]["nullable"] = False
            i += 1
            continue
            
        if "EquivalentClasses" in lines[i] and "rdf" in lines[i]:
            attribute = line.split(":")[2].split(" ")[0].replace(")", "")
            domain = line.split(":")[1].split(" ")[0]
            dict_attributes[attribute]["domain"]["nullable"] = False #no need to work on the range
            i += 1
            continue
        
        if "SubClassOf" in lines[i] and "ObjectUnionOf" not in lines[i]:
            father = line.split(":")[2].replace(")", "")
            child = line.split(":")[1].split(" ")[0]
            dict_classes[child]["isa"] = father
            i += 1
            continue
            
        i += 1

print(dict_classes)
print("************************")
print (dict_relations)
print("************************")
print (dict_attributes)

{'Language': {'attributes': {}}, 'Country': {'attributes': {}}, 'Edition': {'attributes': {}}, 'FictionalHuman': {'attributes': {}}, 'RealCity': {'attributes': {}}, 'Author': {'attributes': {}, 'isa': 'Human'}, 'FictionalNotHuman': {'attributes': {}}, 'FictionalCity': {'attributes': {}}, 'Mayor': {'attributes': {}}, 'Publisher': {'attributes': {}}, 'Translator': {'attributes': {}, 'isa': 'Human'}, 'Character': {'attributes': {}}, 'Book': {'attributes': {}}, 'FictionalCharacter': {'attributes': {}, 'isa': 'Character'}, 'City': {'attributes': {}}, 'Human': {'attributes': {}}}
************************
{'InfluencedBy': {'range': {'nullable': True, 'name': 'Author'}, 'inv_functional': False, 'functional': False, 'domain': {'nullable': True, 'name': 'Author'}}, 'hasCharacter': {'range': {'nullable': False, 'name': 'Character'}, 'inv_functional': False, 'functional': False, 'domain': {'nullable': True, 'name': 'Book'}}, 'hasCountryLocation': {'range': {'nullable': True, 'name': 'Country'}, 'inv_functional': False, 'functional': False, 'domain': {'nullable': True, 'name': 'Book'}}, 'locatedIn': {'range': {'nullable': True, 'name': 'Country'}, 'inv_functional': False, 'functional': True, 'domain': {'nullable': False, 'name': 'Publisher'}}, 'hasMayor': {'range': {'nullable': False, 'name': 'Mayor'}, 'inv_functional': False, 'functional': True, 'domain': {'nullable': True, 'name': 'RealCity'}}, 'BookWrittenIn': {'range': {'nullable': True, 'name': 'Language'}, 'inv_functional': False, 'functional': False, 'domain': {'nullable': False, 'name': 'Book'}}, 'hasCountry': {'range': {'nullable': True, 'name': 'Country'}, 'inv_functional': False, 'functional': False, 'domain': {'nullable': False, 'name': 'RealCity'}}, 'PlaceOfBirth': {'range': {'nullable': True, 'name': 'RealCity'}, 'inv_functional': False, 'functional': True, 'domain': {'nullable': False, 'name': 'Human'}}, 'hasEdition': {'range': {'nullable': False, 'name': 'Edition'}, 'inv_functional': False, 'functional': True, 'domain': {'nullable': True, 'name': 'Book'}}, 'hasForewordAuthor': {'range': {'nullable': True, 'name': 'Author'}, 'inv_functional': False, 'functional': False, 'domain': {'nullable': True, 'name': 'Book'}}, 'PlaceOfDeath': {'range': {'nullable': True, 'name': 'RealCity'}, 'inv_functional': False, 'functional': True, 'domain': {'nullable': True, 'name': 'Human'}}, 'hasUsedLanguage': {'range': {'nullable': False, 'name': 'Language'}, 'inv_functional': False, 'functional': False, 'domain': {'nullable': False, 'name': 'Country'}}, 'hasRole': {'range': {'nullable': False, 'name': 'Mayor'}, 'inv_functional': False, 'functional': False, 'domain': {'nullable': True, 'name': 'Human'}}, 'foundedBy': {'range': {'nullable': True, 'name': 'Human'}, 'inv_functional': False, 'functional': False, 'domain': {'nullable': False, 'name': 'Publisher'}}, 'hasIllustrator': {'range': {'nullable': True, 'name': 'Human'}, 'inv_functional': False, 'functional': False, 'domain': {'nullable': True, 'name': 'Edition'}}, 'hasTranslator': {'range': {'nullable': True, 'name': 'Translator'}, 'inv_functional': False, 'functional': False, 'domain': {'nullable': True, 'name': 'Edition'}}, 'hasCityLocation': {'range': {'nullable': True, 'name': 'City'}, 'inv_functional': False, 'functional': False, 'domain': {'nullable': True, 'name': 'Book'}}, 'hasAuthor': {'range': {'nullable': False, 'name': 'Author'}, 'inv_functional': False, 'functional': False, 'domain': {'nullable': False, 'name': 'Book'}}, 'hasAnalog': {'range': {'nullable': True, 'name': 'RealCity'}, 'inv_functional': False, 'functional': True, 'domain': {'nullable': True, 'name': 'FictionalCity'}}, 'hasPublisher': {'range': {'nullable': False, 'name': 'Publisher'}, 'inv_functional': False, 'functional': False, 'domain': {'nullable': True, 'name': 'Edition'}}, 'speaks': {'range': {'nullable': True, 'name': 'Language'}, 'inv_functional': False, 'functional': False, 'domain': {'nullable': False, 'name': 'Translator'}}, 'hasAfterwordAuthor': {'range': {'nullable': True, 'name': 'Author'}, 'inv_functional': False, 'functional': False, 'domain': {'nullable': True, 'name': 'Book'}}, 'followedBy': {'range': {'nullable': True, 'name': 'Book'}, 'inv_functional': False, 'functional': True, 'domain': {'nullable': True, 'name': 'Book'}}}
************************
{'subtitle': {'range': {'name': 'string'}, 'inv_functional': False, 'functional': True, 'domain': {'nullable': True, 'name': 'Book'}}, 'country_description': {'range': {'name': 'string'}, 'inv_functional': False, 'functional': True, 'domain': {'nullable': False, 'name': 'Country'}}, 'award': {'range': {'name': 'string'}, 'inv_functional': False, 'functional': False, 'domain': {'nullable': True, 'name': 'Author'}}, 'DoD': {'range': {'name': 'string'}, 'inv_functional': False, 'functional': True, 'domain': {'nullable': True, 'name': 'Human'}}, 'character_sex': {'range': {'name': 'string'}, 'inv_functional': False, 'functional': True, 'domain': {'nullable': False, 'name': 'Character'}}, 'city_label': {'range': {'name': 'string'}, 'inv_functional': False, 'functional': True, 'domain': {'nullable': False, 'name': 'City'}}, 'edition_id': {'range': {'name': 'string'}, 'inv_functional': False, 'functional': True, 'domain': {'nullable': False, 'name': 'Edition'}}, 'character_description': {'range': {'name': 'string'}, 'inv_functional': False, 'functional': True, 'domain': {'nullable': False, 'name': 'Character'}}, 'mayor_description': {'range': {'name': 'string'}, 'inv_functional': False, 'functional': True, 'domain': {'nullable': False, 'name': 'Mayor'}}, 'human_description': {'range': {'name': 'string'}, 'inv_functional': False, 'functional': True, 'domain': {'nullable': False, 'name': 'Human'}}, 'country_id': {'range': {'name': 'string'}, 'inv_functional': False, 'functional': True, 'domain': {'nullable': False, 'name': 'Country'}}, 'start_time': {'range': {'name': 'string'}, 'inv_functional': False, 'functional': True, 'domain': {'nullable': False, 'name': 'Mayor'}}, 'language_label': {'range': {'name': 'string'}, 'inv_functional': False, 'functional': True, 'domain': {'nullable': False, 'name': 'Language'}}, 'translator_label': {'range': {'name': 'string'}, 'inv_functional': False, 'functional': True, 'domain': {'nullable': False, 'name': 'Translator'}}, 'translator_description': {'range': {'name': 'string'}, 'inv_functional': False, 'functional': True, 'domain': {'nullable': False, 'name': 'Translator'}}, 'language_id': {'range': {'name': 'string'}, 'inv_functional': False, 'functional': True, 'domain': {'nullable': False, 'name': 'Language'}}, 'book_description': {'range': {'name': 'string'}, 'inv_functional': False, 'functional': True, 'domain': {'nullable': False, 'name': 'Book'}}, 'human_id': {'range': {'name': 'string'}, 'inv_functional': False, 'functional': True, 'domain': {'nullable': False, 'name': 'Human'}}, 'edition_label': {'range': {'name': 'string'}, 'inv_functional': False, 'functional': True, 'domain': {'nullable': False, 'name': 'Edition'}}, 'character_id': {'range': {'name': 'string'}, 'inv_functional': False, 'functional': True, 'domain': {'nullable': False, 'name': 'Character'}}, 'character_DoD': {'range': {'name': 'string'}, 'inv_functional': False, 'functional': True, 'domain': {'nullable': True, 'name': 'Character'}}, 'inception': {'range': {'name': 'string'}, 'inv_functional': False, 'functional': True, 'domain': {'nullable': False, 'name': 'Publisher'}}, 'country_label': {'range': {'name': 'string'}, 'inv_functional': False, 'functional': True, 'domain': {'nullable': False, 'name': 'Country'}}, 'edition_description': {'range': {'name': 'string'}, 'inv_functional': False, 'functional': True, 'domain': {'nullable': False, 'name': 'Edition'}}, 'title': {'range': {'name': 'string'}, 'inv_functional': False, 'functional': True, 'domain': {'nullable': False, 'name': 'Book'}}, 'author_label': {'range': {'name': 'string'}, 'inv_functional': False, 'functional': True, 'domain': {'nullable': False, 'name': 'Author'}}, 'book_label': {'range': {'name': 'string'}, 'inv_functional': False, 'functional': True, 'domain': {'nullable': False, 'name': 'Book'}}, 'city_description': {'range': {'name': 'string'}, 'inv_functional': False, 'functional': True, 'domain': {'nullable': False, 'name': 'City'}}, 'num_speakers': {'range': {'name': 'string'}, 'inv_functional': False, 'functional': True, 'domain': {'nullable': True, 'name': 'Language'}}, 'mayor_id': {'range': {'name': 'string'}, 'inv_functional': False, 'functional': True, 'domain': {'nullable': False, 'name': 'Mayor'}}, 'name': {'range': {'name': 'string'}, 'inv_functional': False, 'functional': True, 'domain': {'nullable': False, 'name': 'Human'}}, 'author_genre': {'range': {'name': 'string'}, 'inv_functional': False, 'functional': False, 'domain': {'nullable': True, 'name': 'Author'}}, 'human_label': {'range': {'name': 'string'}, 'inv_functional': False, 'functional': True, 'domain': {'nullable': False, 'name': 'Human'}}, 'publisher_id': {'range': {'name': 'string'}, 'inv_functional': False, 'functional': True, 'domain': {'nullable': False, 'name': 'Publisher'}}, 'character_name': {'range': {'name': 'string'}, 'inv_functional': False, 'functional': True, 'domain': {'nullable': False, 'name': 'Character'}}, 'DoB': {'range': {'name': 'string'}, 'inv_functional': False, 'functional': True, 'domain': {'nullable': False, 'name': 'Human'}}, 'character_DoB': {'range': {'name': 'string'}, 'inv_functional': False, 'functional': True, 'domain': {'nullable': False, 'name': 'Character'}}, 'author_description': {'range': {'name': 'string'}, 'inv_functional': False, 'functional': True, 'domain': {'nullable': False, 'name': 'Author'}}, 'official_residence': {'range': {'name': 'string'}, 'inv_functional': False, 'functional': True, 'domain': {'nullable': False, 'name': 'Mayor'}}, 'sex': {'range': {'name': 'string'}, 'inv_functional': False, 'functional': True, 'domain': {'nullable': False, 'name': 'Human'}}, 'mayor_label': {'range': {'name': 'string'}, 'inv_functional': False, 'functional': True, 'domain': {'nullable': False, 'name': 'Mayor'}}, 'publisher_label': {'range': {'name': 'string'}, 'inv_functional': False, 'functional': True, 'domain': {'nullable': False, 'name': 'Publisher'}}, 'city_id': {'range': {'name': 'string'}, 'inv_functional': False, 'functional': True, 'domain': {'nullable': False, 'name': 'City'}}, 'language_description': {'range': {'name': 'string'}, 'inv_functional': False, 'functional': True, 'domain': {'nullable': False, 'name': 'Language'}}, 'area': {'range': {'name': 'string'}, 'inv_functional': False, 'functional': True, 'domain': {'nullable': True, 'name': 'RealCity'}}, 'population': {'range': {'name': 'string'}, 'inv_functional': False, 'functional': True, 'domain': {'nullable': True, 'name': 'RealCity'}}, 'end_time': {'range': {'name': 'string'}, 'inv_functional': False, 'functional': True, 'domain': {'nullable': True, 'name': 'Mayor'}}, 'character_label': {'range': {'name': 'string'}, 'inv_functional': False, 'functional': True, 'domain': {'nullable': False, 'name': 'Character'}}, 'book_id': {'range': {'name': 'string'}, 'inv_functional': False, 'functional': True, 'domain': {'nullable': False, 'name': 'Book'}}, 'publisher_description': {'range': {'name': 'string'}, 'inv_functional': False, 'functional': True, 'domain': {'nullable': False, 'name': 'Publisher'}}}

In [8]:
relazioni_da_accorpare = ["hasMayor"]
relazioni_da_accorpare = []
#'character_id': {'range': {'name': 'character_id> xsd:strin'}, 'domain': {'name': 'Character', 'nullable': False}, 'functional': True, 'inv_functional': False}

In [ ]:
#dict_attributes.keys()

In [9]:
for attribute in dict_attributes.keys():
    if dict_attributes[attribute]["functional"] == False: #va reificata la ER-relazione e creata una nuova relazione
        #print(attribute, "**********attr")
        new_class = attribute.title()
        dict_classes[new_class] = {}
        dict_classes[new_class]["attributes"] = {}
        attribute_name = new_class.lower() + "_id"
        dict_classes[new_class]["attributes"][attribute_name] = {}
        dict_classes[new_class]["attributes"][attribute_name]["typ"] = "varchar (255)"
        dict_classes[new_class]["attributes"][attribute_name]["nullable"] = False

        new_relation = "has" + attribute.title()
        dict_relations[new_relation] = {}
        dict_relations[new_relation]["domain"] = {}
        dict_relations[new_relation]["domain"]["name"] = dict_attributes[attribute]["domain"]["name"]
        dict_relations[new_relation]["domain"]["nullable"] = dict_attributes[attribute]["domain"]["nullable"]
        dict_relations[new_relation]["range"] = {}
        dict_relations[new_relation]["range"]["name"] = new_class
        dict_relations[new_relation]["range"]["nullable"] = False
        dict_relations[new_relation]["functional"] = False
        dict_relations[new_relation]["inv_functional"] = False
    else: #assign attributes to classes
        class_ = dict_attributes[attribute]["domain"]["name"]
        #print(class_)
        nullable = dict_attributes[attribute]["domain"]["nullable"]
        typ = "varchar (255)"
        dict_classes[class_]["attributes"][attribute] = {}
        dict_classes[class_]["attributes"][attribute]["typ"] = typ
        dict_classes[class_]["attributes"][attribute]["nullable"] = nullable


for relation in dict_relations.keys():
    if relation in relazioni_da_accorpare and dict_relations[relation]["functional"] == True: #va accorpata, con precedenza sul dominio
        #print(relation, "**********")
        class_ = dict_relations[relation]["domain"]["name"]
        new_attribute = dict_relations[relation]["range"]["name"]
        nullable = dict_relations[relation]["domain"]["nullable"]
        typ = "varchar (255)"
        dict_classes[class_]["attributes"][relation] = {}
        dict_classes[class_]["attributes"][relation]["typ"] = typ
        dict_classes[class_]["attributes"][relation]["nullable"] = nullable
    elif relation in relazioni_da_accorpare and dict_relations[relation]["inv_functional"] == True:
        #print(relation, "*INV**********")
        class_ = dict_relations[relation]["range"]["name"]
        new_attribute = dict_relations[relation]["domain"]["name"]
        nullable = dict_relations[relation]["range"]["nullable"]
        typ = "varchar (255)"
        dict_classes[class_]["attributes"][relation] = {}
        dict_classes[class_]["attributes"][relation]["typ"] = typ
        dict_classes[class_]["attributes"][relation]["nullable"] = nullable
        dict_classes[class_]["attributes"][relation]["references"] = new_attribute
    else: 
        #print(relation)
        domain = dict_relations[relation]["domain"]["name"]
        range_ = dict_relations[relation]["range"]["name"]
        dict_classes[relation] = {}
        dict_classes[relation]["attributes"] = {}
        dict_classes[relation]["attributes"][domain.lower() + "_id"] = {}
        dict_classes[relation]["attributes"][domain.lower() + "_id"]["references"] = domain
        dict_classes[relation]["attributes"][domain.lower() + "_id"]["typ"] = "varchar (255)"
        dict_classes[relation]["attributes"][domain.lower() + "_id"]["nullable"] = dict_relations[relation]["domain"]["nullable"]
        dict_classes[relation]["attributes"][range_.lower() + "_id"] = {}
        dict_classes[relation]["attributes"][range_.lower() + "_id"]["references"] = range_
        dict_classes[relation]["attributes"][range_.lower() + "_id"]["typ"] = "varchar (255)"
        dict_classes[relation]["attributes"][range_.lower() + "_id"]["nullable"] = dict_relations[relation]["range"]["nullable"]

#is-a s
for class_ in dict_classes.keys():
    if "isa" in dict_classes[class_].keys():
        for attr in dict_classes[dict_classes[class_]["isa"]]:
            dict_classes[class_][attr] = dict_classes[dict_classes[class_]["isa"]][attr]
        
        
print(dict_classes)
print("************************")
'''print (dict_relations)
print("************************")
print (dict_attributes)    
print("************************")       '''

{'Language': {'attributes': {'num_speakers': {'nullable': True, 'typ': 'varchar (255)'}, 'language_id': {'nullable': False, 'typ': 'varchar (255)'}, 'language_description': {'nullable': False, 'typ': 'varchar (255)'}, 'language_label': {'nullable': False, 'typ': 'varchar (255)'}}}, 'InfluencedBy': {'attributes': {'author_id': {'references': 'Author', 'nullable': True, 'typ': 'varchar (255)'}}}, 'Author_Genre': {'attributes': {'author_genre_id': {'nullable': False, 'typ': 'varchar (255)'}}}, 'Country': {'attributes': {'country_label': {'nullable': False, 'typ': 'varchar (255)'}, 'country_id': {'nullable': False, 'typ': 'varchar (255)'}, 'country_description': {'nullable': False, 'typ': 'varchar (255)'}}}, 'hasCharacter': {'attributes': {'character_id': {'references': 'Character', 'nullable': False, 'typ': 'varchar (255)'}, 'book_id': {'references': 'Book', 'nullable': True, 'typ': 'varchar (255)'}}}, 'FictionalHuman': {'attributes': {}}, 'locatedIn': {'attributes': {'country_id': {'references': 'Country', 'nullable': True, 'typ': 'varchar (255)'}, 'publisher_id': {'references': 'Publisher', 'nullable': False, 'typ': 'varchar (255)'}}}, 'hasCountryLocation': {'attributes': {'country_id': {'references': 'Country', 'nullable': True, 'typ': 'varchar (255)'}, 'book_id': {'references': 'Book', 'nullable': True, 'typ': 'varchar (255)'}}}, 'hasMayor': {'attributes': {'realcity_id': {'references': 'RealCity', 'nullable': True, 'typ': 'varchar (255)'}, 'mayor_id': {'references': 'Mayor', 'nullable': False, 'typ': 'varchar (255)'}}}, 'BookWrittenIn': {'attributes': {'language_id': {'references': 'Language', 'nullable': True, 'typ': 'varchar (255)'}, 'book_id': {'references': 'Book', 'nullable': False, 'typ': 'varchar (255)'}}}, 'hasCountry': {'attributes': {'realcity_id': {'references': 'RealCity', 'nullable': False, 'typ': 'varchar (255)'}, 'country_id': {'references': 'Country', 'nullable': True, 'typ': 'varchar (255)'}}}, 'FictionalCity': {'attributes': {}}, 'Mayor': {'attributes': {'mayor_description': {'nullable': False, 'typ': 'varchar (255)'}, 'start_time': {'nullable': False, 'typ': 'varchar (255)'}, 'official_residence': {'nullable': False, 'typ': 'varchar (255)'}, 'end_time': {'nullable': True, 'typ': 'varchar (255)'}, 'mayor_id': {'nullable': False, 'typ': 'varchar (255)'}, 'mayor_label': {'nullable': False, 'typ': 'varchar (255)'}}}, 'hasForewordAuthor': {'attributes': {'author_id': {'references': 'Author', 'nullable': True, 'typ': 'varchar (255)'}, 'book_id': {'references': 'Book', 'nullable': True, 'typ': 'varchar (255)'}}}, 'hasAward': {'attributes': {'award_id': {'references': 'Award', 'nullable': False, 'typ': 'varchar (255)'}, 'author_id': {'references': 'Author', 'nullable': True, 'typ': 'varchar (255)'}}}, 'Character': {'attributes': {'character_description': {'nullable': False, 'typ': 'varchar (255)'}, 'character_DoB': {'nullable': False, 'typ': 'varchar (255)'}, 'character_id': {'nullable': False, 'typ': 'varchar (255)'}, 'character_DoD': {'nullable': True, 'typ': 'varchar (255)'}, 'character_name': {'nullable': False, 'typ': 'varchar (255)'}, 'character_sex': {'nullable': False, 'typ': 'varchar (255)'}, 'character_label': {'nullable': False, 'typ': 'varchar (255)'}}}, 'Book': {'attributes': {'book_label': {'nullable': False, 'typ': 'varchar (255)'}, 'book_description': {'nullable': False, 'typ': 'varchar (255)'}, 'subtitle': {'nullable': True, 'typ': 'varchar (255)'}, 'title': {'nullable': False, 'typ': 'varchar (255)'}, 'book_id': {'nullable': False, 'typ': 'varchar (255)'}}}, 'PlaceOfDeath': {'attributes': {'realcity_id': {'references': 'RealCity', 'nullable': True, 'typ': 'varchar (255)'}, 'human_id': {'references': 'Human', 'nullable': True, 'typ': 'varchar (255)'}}}, 'hasUsedLanguage': {'attributes': {'language_id': {'references': 'Language', 'nullable': False, 'typ': 'varchar (255)'}, 'country_id': {'references': 'Country', 'nullable': False, 'typ': 'varchar (255)'}}}, 'Edition': {'attributes': {'edition_label': {'nullable': False, 'typ': 'varchar (255)'}, 'edition_description': {'nullable': False, 'typ': 'varchar (255)'}, 'edition_id': {'nullable': False, 'typ': 'varchar (255)'}}}, 'foundedBy': {'attributes': {'human_id': {'references': 'Human', 'nullable': True, 'typ': 'varchar (255)'}, 'publisher_id': {'references': 'Publisher', 'nullable': False, 'typ': 'varchar (255)'}}}, 'hasIllustrator': {'attributes': {'human_id': {'references': 'Human', 'nullable': True, 'typ': 'varchar (255)'}, 'edition_id': {'references': 'Edition', 'nullable': True, 'typ': 'varchar (255)'}}}, 'hasTranslator': {'attributes': {'translator_id': {'references': 'Translator', 'nullable': True, 'typ': 'varchar (255)'}, 'edition_id': {'references': 'Edition', 'nullable': True, 'typ': 'varchar (255)'}}}, 'hasCityLocation': {'attributes': {'city_id': {'references': 'City', 'nullable': True, 'typ': 'varchar (255)'}, 'book_id': {'references': 'Book', 'nullable': True, 'typ': 'varchar (255)'}}}, 'PlaceOfBirth': {'attributes': {'realcity_id': {'references': 'RealCity', 'nullable': True, 'typ': 'varchar (255)'}, 'human_id': {'references': 'Human', 'nullable': False, 'typ': 'varchar (255)'}}}, 'hasAuthor': {'attributes': {'author_id': {'references': 'Author', 'nullable': False, 'typ': 'varchar (255)'}, 'book_id': {'references': 'Book', 'nullable': False, 'typ': 'varchar (255)'}}}, 'hasAfterwordAuthor': {'attributes': {'author_id': {'references': 'Author', 'nullable': True, 'typ': 'varchar (255)'}, 'book_id': {'references': 'Book', 'nullable': True, 'typ': 'varchar (255)'}}}, 'RealCity': {'attributes': {'population': {'nullable': True, 'typ': 'varchar (255)'}, 'area': {'nullable': True, 'typ': 'varchar (255)'}}}, 'hasEdition': {'attributes': {'edition_id': {'references': 'Edition', 'nullable': False, 'typ': 'varchar (255)'}, 'book_id': {'references': 'Book', 'nullable': True, 'typ': 'varchar (255)'}}}, 'Author': {'attributes': {'human_label': {'nullable': False, 'typ': 'varchar (255)'}, 'human_id': {'nullable': False, 'typ': 'varchar (255)'}, 'sex': {'nullable': False, 'typ': 'varchar (255)'}, 'DoD': {'nullable': True, 'typ': 'varchar (255)'}, 'human_description': {'nullable': False, 'typ': 'varchar (255)'}, 'name': {'nullable': False, 'typ': 'varchar (255)'}, 'DoB': {'nullable': False, 'typ': 'varchar (255)'}}, 'isa': 'Human'}, 'hasAnalog': {'attributes': {'realcity_id': {'references': 'RealCity', 'nullable': True, 'typ': 'varchar (255)'}, 'fictionalcity_id': {'references': 'FictionalCity', 'nullable': True, 'typ': 'varchar (255)'}}}, 'FictionalNotHuman': {'attributes': {}}, 'hasAuthor_Genre': {'attributes': {'author_genre_id': {'references': 'Author_Genre', 'nullable': False, 'typ': 'varchar (255)'}, 'author_id': {'references': 'Author', 'nullable': True, 'typ': 'varchar (255)'}}}, 'Award': {'attributes': {'award_id': {'nullable': False, 'typ': 'varchar (255)'}}}, 'Publisher': {'attributes': {'publisher_label': {'nullable': False, 'typ': 'varchar (255)'}, 'inception': {'nullable': False, 'typ': 'varchar (255)'}, 'publisher_id': {'nullable': False, 'typ': 'varchar (255)'}, 'publisher_description': {'nullable': False, 'typ': 'varchar (255)'}}}, 'hasPublisher': {'attributes': {'publisher_id': {'references': 'Publisher', 'nullable': False, 'typ': 'varchar (255)'}, 'edition_id': {'references': 'Edition', 'nullable': True, 'typ': 'varchar (255)'}}}, 'Translator': {'attributes': {'human_label': {'nullable': False, 'typ': 'varchar (255)'}, 'human_id': {'nullable': False, 'typ': 'varchar (255)'}, 'sex': {'nullable': False, 'typ': 'varchar (255)'}, 'DoD': {'nullable': True, 'typ': 'varchar (255)'}, 'human_description': {'nullable': False, 'typ': 'varchar (255)'}, 'name': {'nullable': False, 'typ': 'varchar (255)'}, 'DoB': {'nullable': False, 'typ': 'varchar (255)'}}, 'isa': 'Human'}, 'speaks': {'attributes': {'language_id': {'references': 'Language', 'nullable': True, 'typ': 'varchar (255)'}, 'translator_id': {'references': 'Translator', 'nullable': False, 'typ': 'varchar (255)'}}}, 'City': {'attributes': {'city_id': {'nullable': False, 'typ': 'varchar (255)'}, 'city_description': {'nullable': False, 'typ': 'varchar (255)'}, 'city_label': {'nullable': False, 'typ': 'varchar (255)'}}}, 'FictionalCharacter': {'attributes': {'character_description': {'nullable': False, 'typ': 'varchar (255)'}, 'character_DoB': {'nullable': False, 'typ': 'varchar (255)'}, 'character_id': {'nullable': False, 'typ': 'varchar (255)'}, 'character_DoD': {'nullable': True, 'typ': 'varchar (255)'}, 'character_name': {'nullable': False, 'typ': 'varchar (255)'}, 'character_sex': {'nullable': False, 'typ': 'varchar (255)'}, 'character_label': {'nullable': False, 'typ': 'varchar (255)'}}, 'isa': 'Character'}, 'hasRole': {'attributes': {'human_id': {'references': 'Human', 'nullable': True, 'typ': 'varchar (255)'}, 'mayor_id': {'references': 'Mayor', 'nullable': False, 'typ': 'varchar (255)'}}}, 'followedBy': {'attributes': {'book_id': {'references': 'Book', 'nullable': True, 'typ': 'varchar (255)'}}}, 'Human': {'attributes': {'human_label': {'nullable': False, 'typ': 'varchar (255)'}, 'human_id': {'nullable': False, 'typ': 'varchar (255)'}, 'sex': {'nullable': False, 'typ': 'varchar (255)'}, 'DoD': {'nullable': True, 'typ': 'varchar (255)'}, 'human_description': {'nullable': False, 'typ': 'varchar (255)'}, 'name': {'nullable': False, 'typ': 'varchar (255)'}, 'DoB': {'nullable': False, 'typ': 'varchar (255)'}}}}
************************

'print (dict_relations)\nprint("************************")\nprint (dict_attributes)    \nprint("************************")       '

In [ ]:
#generate strings and write to file

In [11]:
outstring_create = "CREATE DATABASE bookDB;\n\nUSE bookDB;\n\n"
outstring_insert = ""

with open("create.sql", "w") as cf, open("insert.sql", "w") as insf:
    for class_ in dict_classes.keys():
        referencing = False
        outstring_create += "CREATE TABLE " + class_ + "(" + "\n"
        #print(class_)
        for attribute in dict_classes[class_]["attributes"]:
            outstring_create += "\t" + attribute
            outstring_create +=   " " + dict_classes[class_]["attributes"][attribute]["typ"] 
            if "_id" in attribute:
                outstring_create += " " + " primary key"
            elif not dict_classes[class_]["attributes"][attribute]["nullable"]:
                outstring_create += " " + "not null"
            outstring_create += ",\n"
            if "references" in (dict_classes[class_]["attributes"][attribute]).keys():
                referencing = True
                outstring_create += "\tforeign key " + \
                "("+ attribute + ") references " + \
                dict_classes[class_]["attributes"][attribute]["references"] + "(" + \
                dict_classes[class_]["attributes"][attribute]["references"].lower() + "_id),\n"
        '''for attribute in dict_classes[class_]["attributes"]:
            if "references" in (dict_classes[class_]["attributes"][attribute]).keys():
                outstring_create += "\tprimary key (" + attribute + "," + \
                dict_classes[class_]["attributes"][attribute]["references"].lower() + "_id),\n"'''
        outstring_create = outstring_create.rstrip()[:-1] #remove comma and newline
        outstring_create += ");\n\n" 

        if referencing:
            relative_path = "../roles/" + class_
        else:
            relative_path = "../concepts/" + class_
        outstring_insert += "LOAD DATA LOCAL INFILE \'" +  relative_path + ".txt\' INTO TABLE " + class_ + "\nFIELDS TERMINATED BY ';'\nENCLOSED BY '\"'"+\
        "\nLINES TERMINATED BY '\\n'\nIGNORE 1 LINES;\n\n"


    print(outstring_create)
    print(outstring_insert)
    insf.write(outstring_insert)
    cf.write(outstring_create)

CREATE DATABASE bookDB;

USE bookDB;

CREATE TABLE Language(
	num_speakers varchar (255),
	language_id varchar (255)  primary key,
	language_description varchar (255) not null,
	language_label varchar (255) not null);

CREATE TABLE InfluencedBy(
	author_id varchar (255)  primary key,
	foreign key (author_id) references Author(author_id));

CREATE TABLE Author_Genre(
	author_genre_id varchar (255)  primary key);

CREATE TABLE Country(
	country_label varchar (255) not null,
	country_id varchar (255)  primary key,
	country_description varchar (255) not null);

CREATE TABLE hasCharacter(
	character_id varchar (255)  primary key,
	foreign key (character_id) references Character(character_id),
	book_id varchar (255)  primary key,
	foreign key (book_id) references Book(book_id));

CREATE TABLE FictionalHuman);

CREATE TABLE locatedIn(
	country_id varchar (255)  primary key,
	foreign key (country_id) references Country(country_id),
	publisher_id varchar (255)  primary key,
	foreign key (publisher_id) references Publisher(publisher_id));

CREATE TABLE hasCountryLocation(
	country_id varchar (255)  primary key,
	foreign key (country_id) references Country(country_id),
	book_id varchar (255)  primary key,
	foreign key (book_id) references Book(book_id));

CREATE TABLE hasMayor(
	realcity_id varchar (255)  primary key,
	foreign key (realcity_id) references RealCity(realcity_id),
	mayor_id varchar (255)  primary key,
	foreign key (mayor_id) references Mayor(mayor_id));

CREATE TABLE BookWrittenIn(
	language_id varchar (255)  primary key,
	foreign key (language_id) references Language(language_id),
	book_id varchar (255)  primary key,
	foreign key (book_id) references Book(book_id));

CREATE TABLE hasCountry(
	realcity_id varchar (255)  primary key,
	foreign key (realcity_id) references RealCity(realcity_id),
	country_id varchar (255)  primary key,
	foreign key (country_id) references Country(country_id));

CREATE TABLE FictionalCity);

CREATE TABLE Mayor(
	mayor_description varchar (255) not null,
	start_time varchar (255) not null,
	official_residence varchar (255) not null,
	end_time varchar (255),
	mayor_id varchar (255)  primary key,
	mayor_label varchar (255) not null);

CREATE TABLE hasForewordAuthor(
	author_id varchar (255)  primary key,
	foreign key (author_id) references Author(author_id),
	book_id varchar (255)  primary key,
	foreign key (book_id) references Book(book_id));

CREATE TABLE hasAward(
	award_id varchar (255)  primary key,
	foreign key (award_id) references Award(award_id),
	author_id varchar (255)  primary key,
	foreign key (author_id) references Author(author_id));

CREATE TABLE Character(
	character_description varchar (255) not null,
	character_DoB varchar (255) not null,
	character_id varchar (255)  primary key,
	character_DoD varchar (255),
	character_name varchar (255) not null,
	character_sex varchar (255) not null,
	character_label varchar (255) not null);

CREATE TABLE Book(
	book_label varchar (255) not null,
	book_description varchar (255) not null,
	subtitle varchar (255),
	title varchar (255) not null,
	book_id varchar (255)  primary key);

CREATE TABLE PlaceOfDeath(
	realcity_id varchar (255)  primary key,
	foreign key (realcity_id) references RealCity(realcity_id),
	human_id varchar (255)  primary key,
	foreign key (human_id) references Human(human_id));

CREATE TABLE hasUsedLanguage(
	language_id varchar (255)  primary key,
	foreign key (language_id) references Language(language_id),
	country_id varchar (255)  primary key,
	foreign key (country_id) references Country(country_id));

CREATE TABLE Edition(
	edition_label varchar (255) not null,
	edition_description varchar (255) not null,
	edition_id varchar (255)  primary key);

CREATE TABLE foundedBy(
	human_id varchar (255)  primary key,
	foreign key (human_id) references Human(human_id),
	publisher_id varchar (255)  primary key,
	foreign key (publisher_id) references Publisher(publisher_id));

CREATE TABLE hasIllustrator(
	human_id varchar (255)  primary key,
	foreign key (human_id) references Human(human_id),
	edition_id varchar (255)  primary key,
	foreign key (edition_id) references Edition(edition_id));

CREATE TABLE hasTranslator(
	translator_id varchar (255)  primary key,
	foreign key (translator_id) references Translator(translator_id),
	edition_id varchar (255)  primary key,
	foreign key (edition_id) references Edition(edition_id));

CREATE TABLE hasCityLocation(
	city_id varchar (255)  primary key,
	foreign key (city_id) references City(city_id),
	book_id varchar (255)  primary key,
	foreign key (book_id) references Book(book_id));

CREATE TABLE PlaceOfBirth(
	realcity_id varchar (255)  primary key,
	foreign key (realcity_id) references RealCity(realcity_id),
	human_id varchar (255)  primary key,
	foreign key (human_id) references Human(human_id));

CREATE TABLE hasAuthor(
	author_id varchar (255)  primary key,
	foreign key (author_id) references Author(author_id),
	book_id varchar (255)  primary key,
	foreign key (book_id) references Book(book_id));

CREATE TABLE hasAfterwordAuthor(
	author_id varchar (255)  primary key,
	foreign key (author_id) references Author(author_id),
	book_id varchar (255)  primary key,
	foreign key (book_id) references Book(book_id));

CREATE TABLE RealCity(
	population varchar (255),
	area varchar (255));

CREATE TABLE hasEdition(
	edition_id varchar (255)  primary key,
	foreign key (edition_id) references Edition(edition_id),
	book_id varchar (255)  primary key,
	foreign key (book_id) references Book(book_id));

CREATE TABLE Author(
	human_label varchar (255) not null,
	human_id varchar (255)  primary key,
	sex varchar (255) not null,
	DoD varchar (255),
	human_description varchar (255) not null,
	name varchar (255) not null,
	DoB varchar (255) not null);

CREATE TABLE hasAnalog(
	realcity_id varchar (255)  primary key,
	foreign key (realcity_id) references RealCity(realcity_id),
	fictionalcity_id varchar (255)  primary key,
	foreign key (fictionalcity_id) references FictionalCity(fictionalcity_id));

CREATE TABLE FictionalNotHuman);

CREATE TABLE hasAuthor_Genre(
	author_genre_id varchar (255)  primary key,
	foreign key (author_genre_id) references Author_Genre(author_genre_id),
	author_id varchar (255)  primary key,
	foreign key (author_id) references Author(author_id));

CREATE TABLE Award(
	award_id varchar (255)  primary key);

CREATE TABLE Publisher(
	publisher_label varchar (255) not null,
	inception varchar (255) not null,
	publisher_id varchar (255)  primary key,
	publisher_description varchar (255) not null);

CREATE TABLE hasPublisher(
	publisher_id varchar (255)  primary key,
	foreign key (publisher_id) references Publisher(publisher_id),
	edition_id varchar (255)  primary key,
	foreign key (edition_id) references Edition(edition_id));

CREATE TABLE Translator(
	human_label varchar (255) not null,
	human_id varchar (255)  primary key,
	sex varchar (255) not null,
	DoD varchar (255),
	human_description varchar (255) not null,
	name varchar (255) not null,
	DoB varchar (255) not null);

CREATE TABLE speaks(
	language_id varchar (255)  primary key,
	foreign key (language_id) references Language(language_id),
	translator_id varchar (255)  primary key,
	foreign key (translator_id) references Translator(translator_id));

CREATE TABLE City(
	city_id varchar (255)  primary key,
	city_description varchar (255) not null,
	city_label varchar (255) not null);

CREATE TABLE FictionalCharacter(
	character_description varchar (255) not null,
	character_DoB varchar (255) not null,
	character_id varchar (255)  primary key,
	character_DoD varchar (255),
	character_name varchar (255) not null,
	character_sex varchar (255) not null,
	character_label varchar (255) not null);

CREATE TABLE hasRole(
	human_id varchar (255)  primary key,
	foreign key (human_id) references Human(human_id),
	mayor_id varchar (255)  primary key,
	foreign key (mayor_id) references Mayor(mayor_id));

CREATE TABLE followedBy(
	book_id varchar (255)  primary key,
	foreign key (book_id) references Book(book_id));

CREATE TABLE Human(
	human_label varchar (255) not null,
	human_id varchar (255)  primary key,
	sex varchar (255) not null,
	DoD varchar (255),
	human_description varchar (255) not null,
	name varchar (255) not null,
	DoB varchar (255) not null);


LOAD DATA LOCAL INFILE '../concepts/Language.txt' INTO TABLE Language
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '../roles/InfluencedBy.txt' INTO TABLE InfluencedBy
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '../concepts/Author_Genre.txt' INTO TABLE Author_Genre
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '../concepts/Country.txt' INTO TABLE Country
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '../roles/hasCharacter.txt' INTO TABLE hasCharacter
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '../concepts/FictionalHuman.txt' INTO TABLE FictionalHuman
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '../roles/locatedIn.txt' INTO TABLE locatedIn
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '../roles/hasCountryLocation.txt' INTO TABLE hasCountryLocation
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '../roles/hasMayor.txt' INTO TABLE hasMayor
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '../roles/BookWrittenIn.txt' INTO TABLE BookWrittenIn
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '../roles/hasCountry.txt' INTO TABLE hasCountry
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '../concepts/FictionalCity.txt' INTO TABLE FictionalCity
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '../concepts/Mayor.txt' INTO TABLE Mayor
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '../roles/hasForewordAuthor.txt' INTO TABLE hasForewordAuthor
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '../roles/hasAward.txt' INTO TABLE hasAward
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '../concepts/Character.txt' INTO TABLE Character
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '../concepts/Book.txt' INTO TABLE Book
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '../roles/PlaceOfDeath.txt' INTO TABLE PlaceOfDeath
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '../roles/hasUsedLanguage.txt' INTO TABLE hasUsedLanguage
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '../concepts/Edition.txt' INTO TABLE Edition
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '../roles/foundedBy.txt' INTO TABLE foundedBy
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '../roles/hasIllustrator.txt' INTO TABLE hasIllustrator
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '../roles/hasTranslator.txt' INTO TABLE hasTranslator
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '../roles/hasCityLocation.txt' INTO TABLE hasCityLocation
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '../roles/PlaceOfBirth.txt' INTO TABLE PlaceOfBirth
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '../roles/hasAuthor.txt' INTO TABLE hasAuthor
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '../roles/hasAfterwordAuthor.txt' INTO TABLE hasAfterwordAuthor
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '../concepts/RealCity.txt' INTO TABLE RealCity
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '../roles/hasEdition.txt' INTO TABLE hasEdition
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '../concepts/Author.txt' INTO TABLE Author
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '../roles/hasAnalog.txt' INTO TABLE hasAnalog
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '../concepts/FictionalNotHuman.txt' INTO TABLE FictionalNotHuman
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '../roles/hasAuthor_Genre.txt' INTO TABLE hasAuthor_Genre
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '../concepts/Award.txt' INTO TABLE Award
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '../concepts/Publisher.txt' INTO TABLE Publisher
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '../roles/hasPublisher.txt' INTO TABLE hasPublisher
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '../concepts/Translator.txt' INTO TABLE Translator
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '../roles/speaks.txt' INTO TABLE speaks
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '../concepts/City.txt' INTO TABLE City
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '../concepts/FictionalCharacter.txt' INTO TABLE FictionalCharacter
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '../roles/hasRole.txt' INTO TABLE hasRole
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '../roles/followedBy.txt' INTO TABLE followedBy
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '../concepts/Human.txt' INTO TABLE Human
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

In [16]:
base_iri = "http://books/"
outstring_mappings = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" + \
"<OBDA version=\"1.0\">\n" + \
    "<dataSource databaseDriver=\"org.postgresql.Driver\" databaseName=\"\"\n"+\
        "databasePassword=\"postgres\"\n"+\
        "databaseURL=\"jdbc:postgresql://localhost/comics_db\"\n"+\
        "databaseUsername=\"postgres\" name=\"datasource\"/>\n"+\
    "<prefixes>\n"+\
        "<prefix name=\"owl:\" namespace=\"http://www.w3.org/2002/07/owl#\"/>\n"+\
        "<prefix name=\"rdf:\" namespace=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"/>\n"+\
        "<prefix name=\"sh:\" namespace=\"" + base_iri + "/#>\n"+\
        "<prefix name=\"xsd:\" namespace=\"http://www.w3.org/2001/XMLSchema#\"/>\n"+\
        "<prefix name=\":\" namespace=\"" + base_iri + ">\n"+\
        "<prefix name=\"xml:\" namespace=\"http://www.w3.org/XML/1998/namespace\"/>\n"+\
        "<prefix name=\"rdfs:\" namespace=\"http://www.w3.org/2000/01/rdf-schema#\"/>\n"+\
    "</prefixes>\n"

with open("book_mappings.xml", "w") as mapf:
    
    '''#templates
    outstring_mappings += "<templates>\n"
    for class_ in dict_classes.keys():
        outstring_mappings += "<template>http://books/" + class_.lower() + "_{_}</template>\n"
    outstring_mappings += "</templates>\n"'''
    
    outstring_mappings += "<templates>\n<template>https://www.wikidata.org/wiki/{_}</template>\n<template>{_}</template>\n</templates>\n"
    
    #mappings, sql included
    outstring_mappings += "<mappings>\n"
    mapping_counter = 0
    for class_ in dict_classes.keys():
        mapping_counter += 1
        attributes_set = set()
        from_relation = False
        for attribute in dict_classes[class_]["attributes"]:
            attributes_set.add(attribute)
            if "references" in (dict_classes[class_]["attributes"][attribute]).keys():
                from_relation = True
        if from_relation:
            word = "role"
            domain = "DOM"
            range_ = "RANGE"
        else:
            word = "concept"
        query = "SELECT "
        head_string = "\n<HEAD string=\"" + class_ + "_view("
        for attr in attributes_set:
            query += class_[0].lower() + "." + attr + " AS " + attr + ", "
            head_string += attr + ", "
        head_string = head_string[:-2]
        head_string += ")\"/>"
        query = query[:-2]
        query += " FROM book_db." + class_ + " " + class_[0].lower()
        outstring_mappings += "\n<ontologyPredicateMapping id=\"M" + str(mapping_counter) + "_" + class_ + "\">" + \
        "\n<" + word + " string=" + base_iri + "#" + class_ + ">"
        if not from_relation:
            outstring_mappings += "\n<template>" + base_iri + class_.lower() + "{" + class_.lower() + "_id}" + "</template>"
        else:
            outstring_mappings += "\n<domainTemplate>" + base_iri + domain + "{" + domain + "_id}" + "</domainTemplate>\n<rangeTemplate>" + base_iri + base_iri + range_ + "{" + range_ + "_id}" + "</rangeTemplate>"
        outstring_mappings += "\n</" + word + ">"
        outstring_mappings += head_string + "\n</ontologyPredicateMapping>\n"
        
        for attr in attributes_set:
            mapping_counter += 1
            outstring_mappings += "\n<ontologyPredicateMapping id=\"M" + str(mapping_counter) + "_" + attr + "\">" + \
            "\n<" + "attribute" + " string=" + base_iri + "#" + class_ + ">"
            outstring_mappings += "\n<domainTemplate>" + base_iri + class_.lower() + "{" + class_.lower() + "_id}" + "</domainTemplate>"
            outstring_mappings += "\n<rangeVariable>" + attr + "</rangeVariable> "+ "\n</" + word + ">"
            outstring_mappings += head_string + "\n</ontologyPredicateMapping>\n"
        
        outstring_mappings += "\n<primitiveView>" + "\n<HEAD string=\"" + class_ + "_view(" + class_ + "_id)\"/>" 
        outstring_mappings += "\n<SQLQuery> " + query + " </SQLQuery>\n</primitiveView>\n"
    outstring_mappings += "\n</mappings>\n<blocks/>\n<constraints/>\n</OBDA>"

    print (outstring_mappings)
    mapf.write(outstring_mappings)

<?xml version="1.0" encoding="UTF-8"?>
<OBDA version="1.0">
<dataSource databaseDriver="org.postgresql.Driver" databaseName=""
databasePassword="postgres"
databaseURL="jdbc:postgresql://localhost/comics_db"
databaseUsername="postgres" name="datasource"/>
<prefixes>
<prefix name="owl:" namespace="http://www.w3.org/2002/07/owl#"/>
<prefix name="rdf:" namespace="http://www.w3.org/1999/02/22-rdf-syntax-ns#"/>
<prefix name="sh:" namespace="http://books//#>
<prefix name="xsd:" namespace="http://www.w3.org/2001/XMLSchema#"/>
<prefix name=":" namespace="http://books/>
<prefix name="xml:" namespace="http://www.w3.org/XML/1998/namespace"/>
<prefix name="rdfs:" namespace="http://www.w3.org/2000/01/rdf-schema#"/>
</prefixes>
<templates>
<template>https://www.wikidata.org/wiki/{_}</template>
<template>{_}</template>
</templates>
<mappings>

<ontologyPredicateMapping id="M1_Language">
<concept string=http://books/#Language>
<template>http://books/language{language_id}</template>
</concept>
<HEAD string="Language_view(num_speakers, language_id, language_description, language_label)"/>
</ontologyPredicateMapping>

<ontologyPredicateMapping id="M2_num_speakers">
<attribute string=http://books/#Language>
<domainTemplate>http://books/language{language_id}</domainTemplate>
<rangeVariable>num_speakers</rangeVariable>
</concept>
<HEAD string="Language_view(num_speakers, language_id, language_description, language_label)"/>
</ontologyPredicateMapping>

<ontologyPredicateMapping id="M3_language_id">
<attribute string=http://books/#Language>
<domainTemplate>http://books/language{language_id}</domainTemplate>
<rangeVariable>language_id</rangeVariable>
</concept>
<HEAD string="Language_view(num_speakers, language_id, language_description, language_label)"/>
</ontologyPredicateMapping>

<ontologyPredicateMapping id="M4_language_description">
<attribute string=http://books/#Language>
<domainTemplate>http://books/language{language_id}</domainTemplate>
<rangeVariable>language_description</rangeVariable>
</concept>
<HEAD string="Language_view(num_speakers, language_id, language_description, language_label)"/>
</ontologyPredicateMapping>

<ontologyPredicateMapping id="M5_language_label">
<attribute string=http://books/#Language>
<domainTemplate>http://books/language{language_id}</domainTemplate>
<rangeVariable>language_label</rangeVariable>
</concept>
<HEAD string="Language_view(num_speakers, language_id, language_description, language_label)"/>
</ontologyPredicateMapping>

<primitiveView>
<HEAD string="Language_view(Language_id)"/>
<SQLQuery> SELECT l.num_speakers AS num_speakers, l.language_id AS language_id, l.language_description AS language_description, l.language_label AS language_label FROM book_db.Language l </SQLQuery>
</primitiveView>

<ontologyPredicateMapping id="M6_InfluencedBy">
<role string=http://books/#InfluencedBy>
<domainTemplate>http://books/DOM{DOM_id}</domainTemplate>
<rangeTemplate>http://books/http://books/RANGE{RANGE_id}</rangeTemplate>
</role>
<HEAD string="InfluencedBy_view(author_id)"/>
</ontologyPredicateMapping>

<ontologyPredicateMapping id="M7_author_id">
<attribute string=http://books/#InfluencedBy>
<domainTemplate>http://books/influencedby{influencedby_id}</domainTemplate>
<rangeVariable>author_id</rangeVariable>
</role>
<HEAD string="InfluencedBy_view(author_id)"/>
</ontologyPredicateMapping>

<primitiveView>
<HEAD string="InfluencedBy_view(InfluencedBy_id)"/>
<SQLQuery> SELECT i.author_id AS author_id FROM book_db.InfluencedBy i </SQLQuery>
</primitiveView>

<ontologyPredicateMapping id="M8_Author_Genre">
<concept string=http://books/#Author_Genre>
<template>http://books/author_genre{author_genre_id}</template>
</concept>
<HEAD string="Author_Genre_view(author_genre_id)"/>
</ontologyPredicateMapping>

<ontologyPredicateMapping id="M9_author_genre_id">
<attribute string=http://books/#Author_Genre>
<domainTemplate>http://books/author_genre{author_genre_id}</domainTemplate>
<rangeVariable>author_genre_id</rangeVariable>
</concept>
<HEAD string="Author_Genre_view(author_genre_id)"/>
</ontologyPredicateMapping>

<primitiveView>
<HEAD string="Author_Genre_view(Author_Genre_id)"/>
<SQLQuery> SELECT a.author_genre_id AS author_genre_id FROM book_db.Author_Genre a </SQLQuery>
</primitiveView>

<ontologyPredicateMapping id="M10_Country">
<concept string=http://books/#Country>
<template>http://books/country{country_id}</template>
</concept>
<HEAD string="Country_view(country_label, country_id, country_description)"/>
</ontologyPredicateMapping>

<ontologyPredicateMapping id="M11_country_label">
<attribute string=http://books/#Country>
<domainTemplate>http://books/country{country_id}</domainTemplate>
<rangeVariable>country_label</rangeVariable>
</concept>
<HEAD string="Country_view(country_label, country_id, country_description)"/>
</ontologyPredicateMapping>

<ontologyPredicateMapping id="M12_country_id">
<attribute string=http://books/#Country>
<domainTemplate>http://books/country{country_id}</domainTemplate>
<rangeVariable>country_id</rangeVariable>
</concept>
<HEAD string="Country_view(country_label, country_id, country_description)"/>
</ontologyPredicateMapping>

<ontologyPredicateMapping id="M13_country_description">
<attribute string=http://books/#Country>
<domainTemplate>http://books/country{country_id}</domainTemplate>
<rangeVariable>country_description</rangeVariable>
</concept>
<HEAD string="Country_view(country_label, country_id, country_description)"/>
</ontologyPredicateMapping>

<primitiveView>
<HEAD string="Country_view(Country_id)"/>
<SQLQuery> SELECT c.country_label AS country_label, c.country_id AS country_id, c.country_description AS country_description FROM book_db.Country c </SQLQuery>
</primitiveView>

<ontologyPredicateMapping id="M14_hasCharacter">
<role string=http://books/#hasCharacter>
<domainTemplate>http://books/DOM{DOM_id}</domainTemplate>
<rangeTemplate>http://books/http://books/RANGE{RANGE_id}</rangeTemplate>
</role>
<HEAD string="hasCharacter_view(book_id, character_id)"/>
</ontologyPredicateMapping>

<ontologyPredicateMapping id="M15_book_id">
<attribute string=http://books/#hasCharacter>
<domainTemplate>http://books/hascharacter{hascharacter_id}</domainTemplate>
<rangeVariable>book_id</rangeVariable>
</role>
<HEAD string="hasCharacter_view(book_id, character_id)"/>
</ontologyPredicateMapping>

<ontologyPredicateMapping id="M16_character_id">
<attribute string=http://books/#hasCharacter>
<domainTemplate>http://books/hascharacter{hascharacter_id}</domainTemplate>
<rangeVariable>character_id</rangeVariable>
</role>
<HEAD string="hasCharacter_view(book_id, character_id)"/>
</ontologyPredicateMapping>

<primitiveView>
<HEAD string="hasCharacter_view(hasCharacter_id)"/>
<SQLQuery> SELECT h.book_id AS book_id, h.character_id AS character_id FROM book_db.hasCharacter h </SQLQuery>
</primitiveView>

<ontologyPredicateMapping id="M17_FictionalHuman">
<concept string=http://books/#FictionalHuman>
<template>http://books/fictionalhuman{fictionalhuman_id}</template>
</concept>
<HEAD string="FictionalHuman_vie)"/>
</ontologyPredicateMapping>

<primitiveView>
<HEAD string="FictionalHuman_view(FictionalHuman_id)"/>
<SQLQuery> SELEC FROM book_db.FictionalHuman f </SQLQuery>
</primitiveView>

<ontologyPredicateMapping id="M18_locatedIn">
<role string=http://books/#locatedIn>
<domainTemplate>http://books/DOM{DOM_id}</domainTemplate>
<rangeTemplate>http://books/http://books/RANGE{RANGE_id}</rangeTemplate>
</role>
<HEAD string="locatedIn_view(country_id, publisher_id)"/>
</ontologyPredicateMapping>

<ontologyPredicateMapping id="M19_country_id">
<attribute string=http://books/#locatedIn>
<domainTemplate>http://books/locatedin{locatedin_id}</domainTemplate>
<rangeVariable>country_id</rangeVariable>
</role>
<HEAD string="locatedIn_view(country_id, publisher_id)"/>
</ontologyPredicateMapping>

<ontologyPredicateMapping id="M20_publisher_id">
<attribute string=http://books/#locatedIn>
<domainTemplate>http://books/locatedin{locatedin_id}</domainTemplate>
<rangeVariable>publisher_id</rangeVariable>
</role>
<HEAD string="locatedIn_view(country_id, publisher_id)"/>
</ontologyPredicateMapping>

<primitiveView>
<HEAD string="locatedIn_view(locatedIn_id)"/>
<SQLQuery> SELECT l.country_id AS country_id, l.publisher_id AS publisher_id FROM book_db.locatedIn l </SQLQuery>
</primitiveView>

<ontologyPredicateMapping id="M21_hasCountryLocation">
<role string=http://books/#hasCountryLocation>
<domainTemplate>http://books/DOM{DOM_id}</domainTemplate>
<rangeTemplate>http://books/http://books/RANGE{RANGE_id}</rangeTemplate>
</role>
<HEAD string="hasCountryLocation_view(country_id, book_id)"/>
</ontologyPredicateMapping>

<ontologyPredicateMapping id="M22_country_id">
<attribute string=http://books/#hasCountryLocation>
<domainTemplate>http://books/hascountrylocation{hascountrylocation_id}</domainTemplate>
<rangeVariable>country_id</rangeVariable>
</role>
<HEAD string="hasCountryLocation_view(country_id, book_id)"/>
</ontologyPredicateMapping>

<ontologyPredicateMapping id="M23_book_id">
<attribute string=http://books/#hasCountryLocation>
<domainTemplate>http://books/hascountrylocation{hascountrylocation_id}</domainTemplate>
<rangeVariable>book_id</rangeVariable>
</role>
<HEAD string="hasCountryLocation_view(country_id, book_id)"/>
</ontologyPredicateMapping>

<primitiveView>
<HEAD string="hasCountryLocation_view(hasCountryLocation_id)"/>
<SQLQuery> SELECT h.country_id AS country_id, h.book_id AS book_id FROM book_db.hasCountryLocation h </SQLQuery>
</primitiveView>

<ontologyPredicateMapping id="M24_hasMayor">
<role string=http://books/#hasMayor>
<domainTemplate>http://books/DOM{DOM_id}</domainTemplate>
<rangeTemplate>http://books/http://books/RANGE{RANGE_id}</rangeTemplate>
</role>
<HEAD string="hasMayor_view(realcity_id, mayor_id)"/>
</ontologyPredicateMapping>

<ontologyPredicateMapping id="M25_realcity_id">
<attribute string=http://books/#hasMayor>
<domainTemplate>http://books/hasmayor{hasmayor_id}</domainTemplate>
<rangeVariable>realcity_id</rangeVariable>
</role>
<HEAD string="hasMayor_view(realcity_id, mayor_id)"/>
</ontologyPredicateMapping>

<ontologyPredicateMapping id="M26_mayor_id">
<attribute string=http://books/#hasMayor>
<domainTemplate>http://books/hasmayor{hasmayor_id}</domainTemplate>
<rangeVariable>mayor_id</rangeVariable>
</role>
<HEAD string="hasMayor_view(realcity_id, mayor_id)"/>
</ontologyPredicateMapping>

<primitiveView>
<HEAD string="hasMayor_view(hasMayor_id)"/>
<SQLQuery> SELECT h.realcity_id AS realcity_id, h.mayor_id AS mayor_id FROM book_db.hasMayor h </SQLQuery>
</primitiveView>

<ontologyPredicateMapping id="M27_BookWrittenIn">
<role string=http://books/#BookWrittenIn>
<domainTemplate>http://books/DOM{DOM_id}</domainTemplate>
<rangeTemplate>http://books/http://books/RANGE{RANGE_id}</rangeTemplate>
</role>
<HEAD string="BookWrittenIn_view(language_id, book_id)"/>
</ontologyPredicateMapping>

<ontologyPredicateMapping id="M28_language_id">
<attribute string=http://books/#BookWrittenIn>
<domainTemplate>http://books/bookwrittenin{bookwrittenin_id}</domainTemplate>
<rangeVariable>language_id</rangeVariable>
</role>
<HEAD string="BookWrittenIn_view(language_id, book_id)"/>
</ontologyPredicateMapping>

<ontologyPredicateMapping id="M29_book_id">
<attribute string=http://books/#BookWrittenIn>
<domainTemplate>http://books/bookwrittenin{bookwrittenin_id}</domainTemplate>
<rangeVariable>book_id</rangeVariable>
</role>
<HEAD string="BookWrittenIn_view(language_id, book_id)"/>
</ontologyPredicateMapping>

<primitiveView>
<HEAD string="BookWrittenIn_view(BookWrittenIn_id)"/>
<SQLQuery> SELECT b.language_id AS language_id, b.book_id AS book_id FROM book_db.BookWrittenIn b </SQLQuery>
</primitiveView>

<ontologyPredicateMapping id="M30_hasCountry">
<role string=http://books/#hasCountry>
<domainTemplate>http://books/DOM{DOM_id}</domainTemplate>
<rangeTemplate>http://books/http://books/RANGE{RANGE_id}</rangeTemplate>
</role>
<HEAD string="hasCountry_view(realcity_id, country_id)"/>
</ontologyPredicateMapping>

<ontologyPredicateMapping id="M31_realcity_id">
<attribute string=http://books/#hasCountry>
<domainTemplate>http://books/hascountry{hascountry_id}</domainTemplate>
<rangeVariable>realcity_id</rangeVariable>
</role>
<HEAD string="hasCountry_view(realcity_id, country_id)"/>
</ontologyPredicateMapping>

<ontologyPredicateMapping id="M32_country_id">
<attribute string=http://books/#hasCountry>
<domainTemplate>http://books/hascountry{hascountry_id}</domainTemplate>
<rangeVariable>country_id</rangeVariable>
</role>
<HEAD string="hasCountry_view(realcity_id, country_id)"/>
</ontologyPredicateMapping>

<primitiveView>
<HEAD string="hasCountry_view(hasCountry_id)"/>
<SQLQuery> SELECT h.realcity_id AS realcity_id, h.country_id AS country_id FROM book_db.hasCountry h </SQLQuery>
</primitiveView>

<ontologyPredicateMapping id="M33_FictionalCity">
<concept string=http://books/#FictionalCity>
<template>http://books/fictionalcity{fictionalcity_id}</template>
</concept>
<HEAD string="FictionalCity_vie)"/>
</ontologyPredicateMapping>

<primitiveView>
<HEAD string="FictionalCity_view(FictionalCity_id)"/>
<SQLQuery> SELEC FROM book_db.FictionalCity f </SQLQuery>
</primitiveView>

<ontologyPredicateMapping id="M34_Mayor">
<concept string=http://books/#Mayor>
<template>http://books/mayor{mayor_id}</template>
</concept>
<HEAD string="Mayor_view(official_residence, mayor_id, mayor_label, mayor_description, start_time, end_time)"/>
</ontologyPredicateMapping>

<ontologyPredicateMapping id="M35_official_residence">
<attribute string=http://books/#Mayor>
<domainTemplate>http://books/mayor{mayor_id}</domainTemplate>
<rangeVariable>official_residence</rangeVariable>
</concept>
<HEAD string="Mayor_view(official_residence, mayor_id, mayor_label, mayor_description, start_time, end_time)"/>
</ontologyPredicateMapping>

<ontologyPredicateMapping id="M36_mayor_id">
<attribute string=http://books/#Mayor>
<domainTemplate>http://books/mayor{mayor_id}</domainTemplate>
<rangeVariable>mayor_id</rangeVariable>
</concept>
<HEAD string="Mayor_view(official_residence, mayor_id, mayor_label, mayor_description, start_time, end_time)"/>
</ontologyPredicateMapping>

<ontologyPredicateMapping id="M37_mayor_label">
<attribute string=http://books/#Mayor>
<domainTemplate>http://books/mayor{mayor_id}</domainTemplate>
<rangeVariable>mayor_label</rangeVariable>
</concept>
<HEAD string="Mayor_view(official_residence, mayor_id, mayor_label, mayor_description, start_time, end_time)"/>
</ontologyPredicateMapping>

<ontologyPredicateMapping id="M38_mayor_description">
<attribute string=http://books/#Mayor>
<domainTemplate>http://books/mayor{mayor_id}</domainTemplate>
<rangeVariable>mayor_description</rangeVariable>
</concept>
<HEAD string="Mayor_view(official_residence, mayor_id, mayor_label, mayor_description, start_time, end_time)"/>
</ontologyPredicateMapping>

<ontologyPredicateMapping id="M39_start_time">
<attribute string=http://books/#Mayor>
<domainTemplate>http://books/mayor{mayor_id}</domainTemplate>
<rangeVariable>start_time</rangeVariable>
</concept>
<HEAD string="Mayor_view(official_residence, mayor_id, mayor_label, mayor_description, start_time, end_time)"/>
</ontologyPredicateMapping>

<ontologyPredicateMapping id="M40_end_time">
<attribute string=http://books/#Mayor>
<domainTemplate>http://books/mayor{mayor_id}</domainTemplate>
<rangeVariable>end_time</rangeVariable>
</concept>
<HEAD string="Mayor_view(official_residence, mayor_id, mayor_label, mayor_description, start_time, end_time)"/>
</ontologyPredicateMapping>

<primitiveView>
<HEAD string="Mayor_view(Mayor_id)"/>
<SQLQuery> SELECT m.official_residence AS official_residence, m.mayor_id AS mayor_id, m.mayor_label AS mayor_label, m.mayor_description AS mayor_description, m.start_time AS start_time, m.end_time AS end_time FROM book_db.Mayor m </SQLQuery>
</primitiveView>

<ontologyPredicateMapping id="M41_hasForewordAuthor">
<role string=http://books/#hasForewordAuthor>
<domainTemplate>http://books/DOM{DOM_id}</domainTemplate>
<rangeTemplate>http://books/http://books/RANGE{RANGE_id}</rangeTemplate>
</role>
<HEAD string="hasForewordAuthor_view(book_id, author_id)"/>
</ontologyPredicateMapping>

<ontologyPredicateMapping id="M42_book_id">
<attribute string=http://books/#hasForewordAuthor>
<domainTemplate>http://books/hasforewordauthor{hasforewordauthor_id}</domainTemplate>
<rangeVariable>book_id</rangeVariable>
</role>
<HEAD string="hasForewordAuthor_view(book_id, author_id)"/>
</ontologyPredicateMapping>

<ontologyPredicateMapping id="M43_author_id">
<attribute string=http://books/#hasForewordAuthor>
<domainTemplate>http://books/hasforewordauthor{hasforewordauthor_id}</domainTemplate>
<rangeVariable>author_id</rangeVariable>
</role>
<HEAD string="hasForewordAuthor_view(book_id, author_id)"/>
</ontologyPredicateMapping>

<primitiveView>
<HEAD string="hasForewordAuthor_view(hasForewordAuthor_id)"/>
<SQLQuery> SELECT h.book_id AS book_id, h.author_id AS author_id FROM book_db.hasForewordAuthor h </SQLQuery>
</primitiveView>

<ontologyPredicateMapping id="M44_hasAward">
<role string=http://books/#hasAward>
<domainTemplate>http://books/DOM{DOM_id}</domainTemplate>
<rangeTemplate>http://books/http://books/RANGE{RANGE_id}</rangeTemplate>
</role>
<HEAD string="hasAward_view(award_id, author_id)"/>
</ontologyPredicateMapping>

<ontologyPredicateMapping id="M45_award_id">
<attribute string=http://books/#hasAward>
<domainTemplate>http://books/hasaward{hasaward_id}</domainTemplate>
<rangeVariable>award_id</rangeVariable>
</role>
<HEAD string="hasAward_view(award_id, author_id)"/>
</ontologyPredicateMapping>

<ontologyPredicateMapping id="M46_author_id">
<attribute string=http://books/#hasAward>
<domainTemplate>http://books/hasaward{hasaward_id}</domainTemplate>
<rangeVariable>author_id</rangeVariable>
</role>
<HEAD string="hasAward_view(award_id, author_id)"/>
</ontologyPredicateMapping>

<primitiveView>
<HEAD string="hasAward_view(hasAward_id)"/>
<SQLQuery> SELECT h.award_id AS award_id, h.author_id AS author_id FROM book_db.hasAward h </SQLQuery>
</primitiveView>

<ontologyPredicateMapping id="M47_Character">
<concept string=http://books/#Character>
<template>http://books/character{character_id}</template>
</concept>
<HEAD string="Character_view(character_sex, character_description, character_DoB, character_id, character_DoD, character_name, character_label)"/>
</ontologyPredicateMapping>

<ontologyPredicateMapping id="M48_character_sex">
<attribute string=http://books/#Character>
<domainTemplate>http://books/character{character_id}</domainTemplate>
<rangeVariable>character_sex</rangeVariable>
</concept>
<HEAD string="Character_view(character_sex, character_description, character_DoB, character_id, character_DoD, character_name, character_label)"/>
</ontologyPredicateMapping>

<ontologyPredicateMapping id="M49_character_description">
<attribute string=http://books/#Character>
<domainTemplate>http://books/character{character_id}</domainTemplate>
<rangeVariable>character_description</rangeVariable>
</concept>
<HEAD string="Character_view(character_sex, character_description, character_DoB, character_id, character_DoD, character_name, character_label)"/>
</ontologyPredicateMapping>

<ontologyPredicateMapping id="M50_character_DoB">
<attribute string=http://books/#Character>
<domainTemplate>http://books/character{character_id}</domainTemplate>
<rangeVariable>character_DoB</rangeVariable>
</concept>
<HEAD string="Character_view(character_sex, character_description, character_DoB, character_id, character_DoD, character_name, character_label)"/>
</ontologyPredicateMapping>

<ontologyPredicateMapping id="M51_character_id">
<attribute string=http://books/#Character>
<domainTemplate>http://books/character{character_id}</domainTemplate>
<rangeVariable>character_id</rangeVariable>
</concept>